package project_euler_solutions;

public class Problem_002 {

	public static void main(String[] args) {
		//Problem text:
		//Each new term in the Fibonacci sequence is generated by adding 
		//the previous two terms. By starting with 1 and 2, the first 10 terms will be:

		//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

		//By considering the terms in the Fibonacci sequence whose values
		//do not exceed four million, find the sum of the even-valued terms.
		int limit = 4000000;
		double fibonacci[] = new double[limit];
		fibonacci[0] = 1;
		fibonacci[1] = 2;	//starting off
//		System.out.println("First " + limit + " terms of the Fibonacci sequence:");
//		System.out.print(fibonacci[0] + ", " + fibonacci[1] + ", ");
		
		for(int i = 2; i < limit; i++) {
			fibonacci[i] = fibonacci[i-1] + fibonacci[i-2];
			//System.out.print(fibonacci[i] + ", ");
		}
		System.out.println("...");
		
		long sum = 0;
		for(int i = 0; i < limit; i++) {
			if(fibonacci[i] % 2 == 0 && fibonacci[i] <= 4000000) {
				sum += fibonacci[i];
			}
		}
		System.out.println("Sum of Fibonacci values from 1 to " + limit +": " + sum);
	}

}
